Words and test results routers and services
maximka777/english.learning.server pull request #7
Opened 2017-05-01 19:49 UTC by lebedeanastasija

2017-05-01 20:40 UTC, mbarouski requested changes

2017-05-01 20:40 UTC, maximka777 commented on routes/index.js
> +router.use('/word_topics', require('./wordTopics'));
camelCasePlease

2017-05-01 20:40 UTC, maximka777 commented on routes/testResults/index.js
> +   testResultsService.create(req.body.testResult)
`req.body`

2017-05-01 20:40 UTC, maximka777 commented on routes/wordTopics/index.js
> +   wordTopicsService.create({name: req.body.name})
`req.body`

2017-05-03 19:13 UTC, mbarouski requested changes

2017-05-03 19:13 UTC, maximka777 commented on routes/index.js
> +//router.use(authenticate());
uncomment, please

2017-05-03 19:13 UTC, maximka777 commented on routes/testResults/index.js
> +   testResultsService.getAllByUserIdTestId(req.params.userId, req.params.testId)
how we can get all results of user?

2017-05-03 19:13 UTC, maximka777 commented on services/testResults/index.js
> +    return TestResult.findAll({where: {userId: userId, testId: testId}});
what does it mean... we can have only one result with userId and testId

2017-05-03 19:13 UTC, maximka777 commented on services/wordTopics/index.js
> +        WordTopic.findOrCreate({where: {name: wordTopic.name}, default: {name: wordTopic.name}})
if you use field in `where` you can not use it in defaults

2017-05-03 19:13 UTC, maximka777 commented on services/wordTopics/index.js
> +        WordTopic.findOrCreate({where: {name: wordTopic.name}, default: {name: wordTopic.name}})
`default` => `defaults`

2017-05-03 20:30 UTC, lebedeanastasija commented on routes/testResults/index.js
> +   testResultsService.getAllByUserIdTestId(req.params.userId, req.params.testId)
There is getAllByUserId() function

2017-05-03 20:31 UTC, lebedeanastasija commented on services/testResults/index.js
> +    return TestResult.findAll({where: {userId: userId, testId: testId}});
User can do some test several times

2017-05-03 20:33 UTC, lebedeanastasija commented on services/testResults/index.js
> +    return TestResult.findAll({where: {userId: userId, testId: testId}});
And users results by passing this test can be different

2017-05-03 20:59 UTC, merged